import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  gatheringSidebar: [
    {
      type: 'category',
      label: "Morpeth Gathering",
      link: {
        type: "doc",
        id: 'gathering/index'
      },
      items: [
        {
          type: 'category',
          label: 'Programme',
          link: {
            type: "doc",
            id: "gathering/programme/index"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'gathering/programme'
            }
          ]
        },
        {
          type: 'category',
          label: "Competitions",
          link: {
            type: "doc",
            id: "gathering/competitions/index"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'gathering/competitions'
            },
          ]
        },
        'gathering/gallery',
        'gathering/morpeth-music-cd',
        'gathering/fund-raisers',
        'gathering/become-a-patron',
      ]
    }
  ],
  masSidebar: [
    {
      type: 'category',
      label: "Morpeth Antiquarian Society",
      link: {
        type: "doc",
        id: 'antiquarian-society/index'
      },
      items: [
        'antiquarian-society/newsletter',
        'antiquarian-society/programme-2025-2026',
        'antiquarian-society/publications',
        'antiquarian-society/mas-contact-us',
        'antiquarian-society/roland-bibby'
      ]
    }
  ],
  nlsSidebar: [
    {
      type: 'category',
      label: "Northumbrian Language Society",
      link: {
        type: "doc",
        id: 'language-society/index'
      },
      items: [
        'language-society/news-and-activities',
        'language-society/contact-us',
        'language-society/membership',
        {
          type: 'category',
          label: 'Appendices',
          link: {
            type: "doc",
            id: "language-society/appendices/differences-between-northumbrian-and-standard-english"
          },
          items: [
              'language-society/appendices/differences-between-northumbrian-and-standard-english',
              'language-society/appendices/a-day-oot-wi-me-marras',
              'language-society/appendices/northumberland-northumbria-and-other-diversions'
          ]
        }
      ]
    }
  ],
  magazineSidebar: [
    {
      type: 'category',
      label: "Northumbriana Magazine",
      link: {
        type: "doc",
        id: 'magazine/index'
      },
      items: [
        'magazine/index-of-articles'
      ]
    }
  ],
  eventsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'events'
    }
  ],


  // - below can be deleted...
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],*/

  /*tutorialSidebar: [
    {
      type: 'category',
      label: 'Northumbrian Gathering',
      items: [
        {
          type: 'autogenerated',
          dirName: 'gathering/',
        }
      ]
    },
    {
      type: 'category',
      label: 'Northumbrian Language Society',
      items: [
        {
          type: 'autogenerated',
          dirName: 'language-society',
        }
      ]
    }
  ],*/

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */


};

export default sidebars;
